CREATE TABLE IF NOT EXISTS project (
    id INTEGER,
    user_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    position INTEGER,
    PRIMARY KEY(id AUTOINCREMENT)
);
